### ISSUE TITLE
Update all sites with the new event fellowship deadlines  

### ISSUE THREAD

**Issue by kipkurui** [OBF/obf-docs#108]
Note also that this line on https://www.open-bio.org/event-awards/ needs to be updated:
> Application Deadlines: December 1, 2019, and then, starting in 2020, twice a year, on April 1 and October 1.

_Originally posted by @nlharris in https://github.com/OBF/obf-docs/issues/94#issuecomment-1272631670_

**Comment by nlharris** [comment]
Is this done?

**Comment by kipkurui** [comment]
> Is this done?

Not yet. Let me look at WordPress

**Comment by kipkurui** [comment]
Done!
