### ISSUE TITLE
Introductory posts on Mastodon for OpenBio and BOSC

### ISSUE THREAD

**Issue by nlharris** [OBF/obf-docs#109]
up to 500 chars each

**Comment by peterjc** [comment]
Should include the hashtag #introduction (Mastodon convention, explicitly requested on some instances), and assorted others like #bioinformatics and #OpenSource (note camel case, important for screen readers to detect the word boundary). These are the primary search mechanism on Mastodon (free text search is limited).

We may want to refine the profile text too, currently:

* https://genomic.social/@OpenBio - The Open Bioinformatics Foundation (OBF) is a non-profit, volunteer-run organization that supports #OpenSource #bioinformatics. Our member projects include #BioPerl, #BioJava, #BioRuby and #Biopython. We run an annual meeting, the Bioinformatics Open Source Conference (@BOSC).
* https://genomic.social/@BOSC - #Bioinformatics #OpenSource Conference (BOSC), run by the Open Bioinformatics Foundation (OBF, @OpenBio).

**Comment by nlharris** [comment]
- [ ] @OpenBio
- [ ] @BOSC
