### ISSUE TITLE
Reduce process for candidate openbio projects

### ISSUE THREAD

**Issue by chapmanb** [OBF/obf-docs#14]
Hilmar, Pjotr and all;
An issue for discussion at BOSC. To help reduce the number of steps to become an affiliated project, I'd suggest removing the `Candidate OBF project` status and having a two tiered hierarchy of `Core` and `Affiliated`:

https://github.com/OBF/obf-docs/blob/unratified-drafts/Affiliated-Project-Policy.md#candidate-obf-project

As written, the process is rather lengthy and projects submitting for `Affiliated` status should already be previously known in the OBF community, either through developer relationships or presentations at BOSC.

**Comment by hlapp** [comment]
The current version of the policy at #44 maintains the _Candidate OBF Project_ status. I feel this is necessary for actually having a process, one of the major goals of the policy to start with.

**Comment by yochannah** [comment]
I'm inclined to agree with this - "candidate" is essentially a label for a project which has made itself aware to the board as interested in joining, that hasn't been rejected out of hand for some reason. It is meaningful and useful.

**Comment by hlapp** [comment]
I believe this is now addressed with the change in #55. If anyone disagrees, please comment what is missing and reopen the issue.
