### ISSUE TITLE
Make explicit the frequency of voting

### ISSUE THREAD

**Issue by hlapp** [OBF/obf-docs#19]
Procedural questions related to voting: Is it the case that voting on project status occurs only once/year?  If so, perhaps at BOSC, with a concurrent email ballot?   If that is the case, it would be helpful explicitly say so.  (I actually think once/year at BOSC is a good idea, so I'm not objecting here, just suggesting a specific statement.)

Reported by @longb.

**Comment by kcranston** [comment]
Up to a year seems like a long time to wait for a project that is seeking new status / change of status.

**Comment by peterjc** [comment]
On the other hand, some very relevant projects like BioLib started up but was not able to be sustained.

**Comment by hlapp** [comment]
I don't think the policy has to specify the frequency. Personally, I think once a year is a good frequency to start with. I also think changing that frequency if and when experience suggests so shouldn't require changing the governing policy.

**Comment by hlapp** [comment]
The current draft of the policy says in [_Community voting on project status_](https://github.com/OBF/obf-docs/blob/affiliated-projects-policy/Affiliated-Project-Policy.md#community-voting-on-project-status):
> Projects can change or attain an affiliation status once a year by a vote of the OBF community.

So it is pretty explicit, and it is actually in the policy. It seems we've been OK with this, so I propose to close this issue. Please object if you feel this shouldn't be in the policy at all, or that a different frequency is needed. (Though if the latter, note that BOSC takes place annually, and that putting votes in front of the membership outside of BOSC more frequently than once a year may well lead to voting fatigue. So please then suggest a mechanism for conducting the ballot casting that you believe is reasonably feasible.

**Comment by yochannah** [comment]
I agree - this is suitable to close. We can re-open if we have further comments.
