### ISSUE TITLE
What does "a majority of 70% is required" mean?

### ISSUE THREAD

**Issue by hlapp** [OBF/obf-docs#22]
Procedural question related to voting: What does "a majority of 70% is required" mean?  Is it of the total membership (hard to achieve, and hard to determine since non-OBF members can vote), or just of the ballots actually cast?   If the later, is there a minimum number of votes needed? (One could imaging a pathological case of only 4 votes, with 3 promoting a position most people would oppose had they bothered to vote.)

Reported by @longb.

**Comment by kcranston** [comment]
Agreed that "a majority of 70%" is unclear. 70% is also really high. Is there a justification for that number? What sort of turnout do we generally get for other votes? Is extremely low turnout and therefore biased results a realistic outcome? I assume that the board members also vote. 

Saying "x% of the cast ballots must approve the membership request" seems reasonable (where x=70 or some other number).

**Comment by hlapp** [comment]
Fixed in 6b4907e506cadeca0f66f38f7399318b0f1b48a2
