### ISSUE TITLE
Allow non-board reviewers for the OBF Travel Fellowship

### ISSUE THREAD

**Issue by peterjc** [OBF/obf-docs#27]
Re: https://github.com/OBF/obf-docs/blob/master/Travel_fellowships.md

> **Who will review the applications?**
> The applications will be considered by the OBF Board of Directors. Individual directors with a clear conflict of interest will recuse themselves.

As discussed yesterday, we would like to expand this for the second and future calls to allow for additional external reviewers (e.g. drawing on the BOSC community or otherwise). For transparency, should we commit to listing the reviewers as part of announcing the results of each call?

**Comment by kcranston** [comment]
[This commit](https://github.com/OBF/obf-docs/commit/4d0ee866df61679f2be80155e71fa527f8d0686d#diff-ce8ffb05c352ae3427a9d37fbd15dfc8R27) added 'OBF members' to the list of potential reviewers. 

I think listing the reviewers is something we should do in the blog post where we announce the awardees, but not sure we need to commit to doing that in the fellowship docs. Open to other opinions, though.

**Comment by yochannah** [comment]
+1 agree - list reviewers good, don't have to codify in the docs.

**Comment by peterjc** [comment]
Excellent, since that has been changed (as part of #41), I think we can close this issue.
