### ISSUE TITLE
Limiting the number of OBF projects

### ISSUE THREAD

**Issue by kcranston** [OBF/obf-docs#38]
In the [Motivation Section](https://github.com/OBF/obf-docs/blob/unratified-drafts/Affiliated-Project-Policy.md#motivation) of the Affiliated Project Proposal, we say that "the group of projects with some status of affiliation with the OBF is expected to always be limited in number" but give no mechanisms for limiting projects. One of more of the following would be possible:

* a mechanism for projects to lose affiliated status (i.e. because they become inactive, no longer play a role as OBF volunteers, change to closed-source, etc)
* a gatekeeper role for the OBF board to review proposals before they go to the membership for voting (i.e. saying "in this year, we can only accept X membership requests")
* having the board and / or membership review *all* projects on a regular basis
* have the vote be a ranking of proposals, rather than a yes / no for each one

Other thoughts?

**Comment by yochannah** [comment]
I doubt we'll ever be over loaded with too many projects wanting to be affiliated, although that might be a great problem to have! Given this, I don't strongly feel that we need to have an explicit limit or process to force a limited number of projects, but we could re-review it if there ever seems to be too many projects.

We've also recently added details on how [inactive projects might become archived](https://github.com/OBF/obf-docs/pull/44/files#diff-e8de1ca0ca53a15cdf7e47387cdd5151R143) which can allow us to prune the list if we note projects are no longer maintained.

**Comment by hlapp** [comment]
I too lean to defer instituting a formal cap on the number of member projects to a future policy change if and when this does become necessary. Until then, any such number seems necessarily arbitrary, at least in the absence of an actual "per-project cost" analysis.

**Comment by HLWiencko** [comment]
It looks like this sentence doesn't need to be a thing: `Therefore, the group of projects with some status of affiliation with the OBF is expected to always be limited in number.` It's a non-sequitur, and causes confusion? 

If we want, we can add a sentence somewhere in the document `There does not need to be a cap on the number of OBF member projects as of the writing of this policy.`

**Comment by nlharris** [comment]
Good idea. How about this minor variation: "As of the writing of this policy, there is no cap on the number of projects that can become OBF member projects."

**Comment by hlapp** [comment]
We decided to leave the following sentence in the policy: _Therefore, the group of projects with some status of affiliation with the OBF is expected to always be limited in number._
