### ISSUE TITLE
Clarify awardee logistics guidance and/or expectations 

### ISSUE THREAD

**Issue by hlapp** [OBF/obf-docs#40]

**Comment by kcranston** [comment]
Can you add a little more detail about what you mean here?

**Comment by hlapp** [comment]
The blog post requirement is now clarified (#48). Logistics might include reimbursement instructions, but I'm not sure that's stable enough and also free of information not meant for public Google'able consumption. So maybe this is it?

**Comment by nlharris** [comment]
I think this has been sufficiently addressed by the changes we just made in #48, and this issue can be closed.

**Comment by hlapp** [comment]
Closing - can always be reopened if others disagree.
