### ISSUE TITLE
SVG+Text logos not necessarily rendering correctly

### ISSUE THREAD

**Issue by yochannah** [OBF/obf-docs#53]
Compare the svg (top) to png (bottom) as rendered on my machine - we need to convert the svg text to curves to make sure it renders consistently. 

<img width="615" alt="image" src="https://user-images.githubusercontent.com/9271438/52819881-65aa3700-30a2-11e9-8ae3-21c59bdd6b07.png">
<img width="615" alt="image" src="https://user-images.githubusercontent.com/9271438/52819900-7490e980-30a2-11e9-9d1c-c7ee9e8e73a9.png">

**Comment by hlapp** [comment]
Could it be that you don’t have the necessary font installed?

**Comment by yochannah** [comment]
Possibly! We shouldn't rely on people having that font for it to render
correctly, though - text converted to a vector shape will render fine no
matter what fonts a machine has.

**Comment by yochannah** [comment]
I've added the hacktoberfest label to this issue - see the /logos folder in this repo to find the relevant files. I think what we need to do is create versions of the file that have the text converted to curves in the correct font, _as well as_ keeping the existing files (for editing purposes).

**Comment by Hrittik20** [comment]
Hi @yochannah, I would like to help with this issue. We only need to convert the svg (top) to curve/outline, right?

**Comment by Hrittik20** [comment]
I have created a pull request to add the new curve file. You can check it out and let me know if I need to change or add anything more.
