### ISSUE TITLE
Reconcile / revise application process for Affiliate and Candidate projects

### ISSUE THREAD

**Issue by hlapp** [OBF/obf-docs#56]
There is currently a template for Affiliate OBF Project application mentioned in the policy FAQ, but the main policy document still contains a link to the same template, for Candidate OBF Project applications.

- [x] ~Need to move both into the FAQ document.~ - n/a not required
- [x] Need to decide whether we need one or two templates. (One only)
- [x] Make corresponding changes to FAQ document.
- [x] ~Create second template if deemed necessary.~ - n/a not required

**Comment by hlapp** [comment]
@yochannah (and/or @HLWiencko) your thoughts?

**Comment by yochannah** [comment]
So, I suggest one template - for candidate projects. Candidate projects should be discussed by default at public board meetings and voted upon if they've had the requisite one year candidate status when the board meeting occurs. I doubt anything different would be needed in the candidate->affiliate status apart from time elapsed.

**Comment by yochannah** [comment]
#59 addresses this - after looking through the FAQ I don't believe many changes were needed.

**Comment by hlapp** [comment]
Looks like this is now addressed in full with #59.
