### ISSUE TITLE
"Deprecated Project" or "Inactive Project" status?

### ISSUE THREAD

**Issue by peterjc** [OBF/obf-docs#61]
Should there be a "Deprecated Project" or "Inactive Project" status for formerly "Affiliated Projects" which have not been ejected, but simply stopped?

We could grandfather a few, e.g. BioMoby.

The main benefit is a historical record (for both OBF and the project), but possible concrete  benefits might include maintaining any custom project domain names (perhaps with a time limit)?

This would overlap with the work on #14: we would need some process - ideally the project leadership could request this, and/or the OBF board could impose it in the event that a project becomes inactive and the former leadership cannot be reached.

**Comment by hlapp** [comment]
I agree that's worth discussing. I've in fact weighed that in my mind when making the latest changes, but in the end decided to start with simply sticking to the categorization on the wiki.

One way to look at this could be to not take guidance from the current version on the wiki (which was then migrated to the new website), but use the wiki's version history to turn the clock back some amount and use the version from then as the guidance.

**Comment by hlapp** [comment]
We decided that no such status is needed in the policy, but the policy contains sections on status maintenance and grandfathering that address this.
