### ISSUE TITLE
Add an over-arching code of conduct for OBF projects

### ISSUE THREAD

**Issue by yochannah** [OBF/obf-docs#67]
Launch blog here - https://www.open-bio.org/2019/11/15/creating-an-obf-wide-code-of-conduct/ 

Anyone is welcome to comment with constructive ideas, especially regarding some of the questions raised in the blog post. Alternatively, email board [ at ] open-bio [ dot ] org.

**Comment by yochannah** [comment]
Some great comments on twitter from @kirstiejane:

https://twitter.com/kirstie_j/status/1196122419301421058 
>Awesome points to consider! Glad you and @obf_news are thinking through this step so carefully! I like the carpentries CoC & I think having multiple reporting points is important for when folks in leadership are involved.

>If there are events where 2 CoC could conflict (I guess from a project and an event community?) it seems like there should be agreement beforehand which one would take precedent. It doesn’t feel hard to agree on if you don’t wait until something has gone wrong?

**Comment by michaelmhoffman** [comment]
Thank you for doing this!

Regarding one of the questions asked in the blog post, multiple reporting points is a good idea. I wouldn't worry too much about the corner case where someone has a complaint against the entire board. I would suggest that if someone has a complaint where any subset of board members is involved they could bring it up to any other board member.

**Comment by yochannah** [comment]
https://twitter.com/gvwilson/status/1196448242889822214?s=19 some great resources from Greg Wilson 😍

**Comment by peterjc** [comment]
Bio* project mailing list posts:

* https://mailman.open-bio.org/pipermail/biopython/2019-November/016730.html
* https://mailman.open-bio.org/pipermail/biosql-l/2019-November/002824.html
* https://mailman.open-bio.org/pipermail/bioperl-l/2019-November/089422.html
* https://mailman.open-bio.org/pipermail/biojava-l/2019-November/011559.html

**Comment by heuermh** [comment]
Thanks for opening this issue!  I have a few questions.

____First:____

Will the same Code of Conduct necessarily be appropriate for both software projects and for in-person events?

____Second:____

We've adapted the [Contributor Covenant](https://www.contributor-covenant.org/) in [ADAM](https://github.com/bigdatagenomics/adam) and other [Big Data Genomics](https://github.com/bigdatagenomics) projects.

In our Code of Conduct, we use a project leadership team for reporting and enforcement, and then one of our PIs as an escalation contact, for reporting an issue with the project leadership team.

https://github.com/bigdatagenomics/adam/blob/master/CODE_OF_CONDUCT.md#enforcement
https://github.com/bigdatagenomics/adam/blob/master/CODE_OF_CONDUCT.md#escalation

For affiliated projects, with this OBF-wide Code of Conduct, is the intention that the OBF board be the contact for reporting and enforcement, with an ombundsperson for escalation, or might it be reporting and enforcement to project leadership teams, and escalation to the OBF board?

____Third:____

Will the OBF board seek training and legal advice on how to properly handle reported issues and enforcement?  If project leadership teams are responsible for those roles, can such training and legal advice also be made available to them?

Thank you!

**Comment by peterjc** [comment]
Answering @heuermh with my understanding as one of the board, but not necessarily the consensus or final policy:

1. We're hoping to have a single CoC for both online and in person, both projects and meetings. As an example, The Carpentries CoC seems to cover this.

2. With an OBF wide CoC, we would expect there to be a single contact (saving the member projects from having to handle this themselves). If a project seeking to formally join the OBF to already have its own CoC (like ADAM does), my personal view is they wouldn't _necessarily_ need to adopt the OBF CoC instead, but that would at least be an option.

3. Training for handling and enforcement - absolutely. I'm not sure if we have discussed legal advice.

Answering @KirstieJane's question about joint events, yes - my expectation is there would be a single CoC agreed in advance. We have precedent with the OBF's meeting BOSC, which has followed the ISCB CoC when held as part of their ISMB conference, and followed the Galaxy community's CoC for GCCBOSC2018 when we held a joint meeting.

**Comment by peterjc** [comment]
We have published a blog post about the draft CoC (see #78), requesting comments by 4 June 2021:

https://www.open-bio.org/2021/05/12/request-for-comments-on-coc-draft/
