### ISSUE TITLE
Is EMBOSS abandonware? 

### ISSUE THREAD

**Issue by hinz1** [OBF/obf-docs#69]
Hi. 

I just tried to download EMBOSS. The emboss website links to ftp://emboss.open-bio.org which doesn't seem to exist anymore and the open-bio website links to the emboss website. That's kind of circular. ;) 
There doesn't seem to be a working rpm file to be found that doesn't send you into dependency hell. Getting sources isn't easy as explained above. The only thing that still works seems to be installing from Ubuntu-Repos. 

Would be a pity if this tool collection should vanish. 

Best,
Markus

**Comment by peterjc** [comment]
Let's start with some good news: the latest source code - ftp://emboss.open-bio.org/pub/EMBOSS/ still works and has the EMBOSS 6.6.0 tar-ball which is to my knowledge the latest release:

ftp://emboss.open-bio.org/pub/EMBOSS/EMBOSS-6.6.0.tar.gz

EMBOSS unfortunately failed to make a smooth transition from a funded project with full time staff to a volunteer managed project. In parallel with this, most of the OBF hosted servers have been retired, with the still active associated projects now hosted on GitHub and using GitHub pages for their websites.

Repository - the old CVS server ``cvs.open-bio.org`` is offline, but I believe Peter Rice had access to a backup and was trying a git migration (the route that Biopython successfully followed many years back), but that seems to have stalled with just https://github.com/peterrice/EMBOSS (practically empty right now). Sadly someone else got the EMBOSS username on GitHub.

I would need to try getting in touch with Peter Rice again by email, but would think https://github.com/OBF/EMBOSS would be a good place for this. We (OBF volunteers) might have to do this from the OBF CVS server backups.

Failing that, we could reconstruct a skeleton history using the old tar-balls from ftp://emboss.open-bio.org/pub/EMBOSS/old/ and a script like https://github.com/peterjc/tarball2git

**Comment by peterjc** [comment]
Peter Rice replied by email that he is still working on resurrecting a repository and the wiki.

**Comment by hinz1** [comment]
That's good news. Thank you very much for your reply. Which mailing list should I join to stay up-to-date?

**Comment by peterjc** [comment]
This one, although it is very quiet:

https://mailman.open-bio.org/mailman/listinfo/emboss aka
https://lists.open-bio.org/mailman/listinfo/emboss

**Comment by nlharris** [comment]
EMBOSS is still listed on https://www.open-bio.org/projects/#member-projects
Can we move it to Retired Projects

**Comment by peterjc** [comment]
We can always move it back again if Peter Rice does have a GitHub repository to share...

**Comment by nlharris** [comment]
Ok, EMBOSS moved to retired.

What about BioDAS, is that also retired?

**Comment by peterjc** [comment]
It would appear to be yes, nothing on the BioDAS mailing list or Wiki in years.

**Comment by hlapp** [comment]
> What about BioDAS, is that also retired?

Yes, it hasn't been active for years.
