### ISSUE TITLE
Add required reviewer approval for OBF docs

### ISSUE THREAD

**Issue by cjfields** [OBF/obf-docs#72]
See:

https://help.github.com/en/github/administering-a-repository/about-required-reviews-for-pull-requests

We should probably think about how we want to do this, as we can also use protected branches in a similar manner to prevent accidental merges.

https://help.github.com/en/github/administering-a-repository/configuring-protected-branches

**Comment by peterjc** [comment]
+1 on protecting the master branch so it can only be changed via a pull request which has had a review approval (seems a reasonable low bar to prevent accidents).

This would be in addition to the formal board meeting approval needed for minutes or policy changes.

**Comment by cjfields** [comment]
See #71 for the branch rule in effect; this can be tweaked here:

https://github.com/OBF/obf-docs/settings/branches

**Comment by hlapp** [comment]
Great, thanks for enabling this. I don't know why we didn't think of doing this earlier.

**Comment by cjfields** [comment]
Closing this out now it's in place.
