### ISSUE TITLE
Vote on name change: OBF Travel fellowship -> OBF Event Fellowship

### ISSUE THREAD

**Issue by malvikasharan** [OBF/obf-docs#80]
# Summary

* With the ongoing pandemic, the scope of our travel fellowship has expanded to support virtual events so the name doesn't fit anymore. At the board meeting, we talked about changing the name to reflect the scope.

## What is this PR for?

- OBF members need to approve the name change of the travel fellowship to Event fellowship

## How to do it?

- Thumbs-up emoji to add your +1
- If you disagree with the name or want to discuss this further, please respond below with a comment

**Comment by nlharris** [comment]
This has been done
