### ISSUE TITLE
[design task] create twitter header image

### ISSUE THREAD

**Issue by yochannah** [OBF/obf-docs#82]
Use the logos in this repo's /logo directory for inspiration and make sure to size it correctly, but other than that, let your creativity run free. See https://blog.snappa.com/twitter-header-size/ for header size info.

Comment on this issue if you're interested in picking this up. You may also be interested in #81 at the same time / in the same theme (but make sure to make two PRs for full hacktoberfest credit!)

Specs:
- correct size for a twitter header banner
- matches current OBF green colour theme and font
- required: svg and raster png/jpg files, other files (e.g. psd or .ai) optional.

**Comment by Manoj13-coder** [comment]
Assign this one to me

**Comment by peterjc** [comment]
Also would be used for the Mastodon header, https://genomic.social/@OpenBio - target resolution there is 1500x500, see https://docs.joinmastodon.org/user/profile/#header

**Comment by VARUN-009** [comment]
I would love to work on this. Please assign me on this.

**Comment by itssiddhantjain** [comment]
I want to work on this issue. Please assign me this issue.

**Comment by subhamkumarr** [comment]
Please assign this to me @GSOC'24

**Comment by peterjc** [comment]
We're not using Twitter anymore - https://www.open-bio.org/2023/11/20/leaving-x/

Having a header image for Mastodon might be nice though...
