### ISSUE TITLE
Affiliated project policy on main website

### ISSUE THREAD

**Issue by peterjc** [OBF/obf-docs#83]
https://www.open-bio.org/projects/ needs a brief header about adding projects, linking to https://github.com/OBF/obf-docs/blob/master/Affiliated-project-FAQ.md and https://github.com/OBF/obf-docs/blob/master/Affiliated-Project-Policy.md

**Comment by Arnab11917676** [comment]
Hello Peter,
I want to work on this issue regarding linking the main website with the subsidiary links on Github by adding a brief header in it.

**Comment by yochannah** [comment]
Hey @Arnab11917676 - thanks for the offer! in this case I think it needs to be handled by someone who has permissions to update the site via wordpress (Rather than via github) - thanks for the offer though! 🙌

**Comment by nlharris** [comment]
@hzahroh perhaps this is something you could tackle.

**Comment by hzahroh** [comment]
Sure, let me try @nlharris

**Comment by hzahroh** [comment]
@peterjc @nlharris I added "adding projects" as a submenu, also added FAQ and descriptions there. Please check whether this is what you had in mind. 
<img width="1792" alt="Screenshot 2022-03-16 at 09 42 07" src="https://user-images.githubusercontent.com/70099457/158506233-7b31546e-1095-4acb-bf20-bfcdeea76356.png">

**Comment by nlharris** [comment]
nice! thanks so much!!
