### ISSUE TITLE
Do we still need clause that states that pre-existing OBF projects were granted affiliated status?

### ISSUE THREAD

**Issue by malvikasharan** [OBF/obf-docs#91]
Moving discussion from #90 

The [Affiliated Project Policy](https://github.com/OBF/obf-docs/blob/event-fellowship-rubric/Affiliated-Project-Policy.md) has a clause stating that pre-existing OBF projects were granted affiliated status, *followed by one allowing other projects to be grandfathered*. This issue is to discuss if we still need *that second clause*:

> Other projects that existed prior to enactment of this policy can be grandfathered to Affiliated or Candidate OBF Project status as well upon approval by the OBF Board of Directors. It is expected that the Board will do so in public session. For pre-existing projects grandfathered to Candidate OBF Project status the minimum waiting period for seeking Affiliate OBF Project status is waived.

Specific comment by @peterjc: 

> "I looked back at https://github.com/OBF/obf-docs/pull/44, but don't immediately see any discussion there of this entire clause. It seems like a board approved short-cut of the process, which may have been sense when the policy was new and there were a couple of potential new affiliations on the horizon, but do we still need it?"

**Comment by peterjc** [comment]
Thanks Malvika, I agree this deserves its own issue.

**Comment by hlapp** [comment]
Well, at this point _all_ OBF Affiliated Projects have that status because of legacy. But maybe I'm not understanding the question or issue?

**Comment by peterjc** [comment]
This was the paragraph I was questioning:

> Other projects that existed prior to enactment of this policy can be grandfathered to Affiliated or Candidate OBF Project status as well upon approval by the OBF Board of Directors. It is expected that the Board will do so in public session. For pre-existing projects grandfathered to Candidate OBF Project status the minimum waiting period for seeking Affiliate OBF Project status is waived.
